### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by Vinita6103** [PaulHoOutsystems/stripe_odc_connector#1]
I am using stripe odc connector but getting following error when i call create payment intent
OS-ELRT-60008 - Stripe.StripeException: The search feature is temporarily unavailable in your region.
![errorStripe](https://github.com/user-attachments/assets/0ba76190-3015-4396-be24-acae6b0f8489)

please guide me how can i use this connector

**Comment by PaulHoOutsystems** [comment]
Hi @Vinita6103 ,

You might want to check the ODC logs to get more information to the error. You should first check that the STRIPE_API_KEY is set up correctly. Please refer to [here](https://github.com/PaulHoOutsystems/stripe_odc_connector/blob/main/README.md#configuration).
